# Generated by Django 3.2 on 2021-04-19 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0001_initial'),
        ('keyresults', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyresults',
            name='objective',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='objectives.objective'),
        ),
    ]
