# Generated by Django 3.2 on 2021-04-19 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0001_initial'),
        ('keyresults', '0002_keyresults_objective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyresults',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyresults', to='objectives.objective'),
        ),
    ]
