# Generated by Django 3.1.7 on 2021-04-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_objectives'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Objective',
        ),
    ]
